name: Sailfish build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm

      - name: Build RPM
        run: |
          docker run --rm \
            -v "$GITHUB_WORKSPACE:/source" \
            ghcr.io/sailfishos-open/docker-sailfishos-builder-armv7hl:5.1.0.11 \
            buildrpm \
            -r https://repo.sailfishos.org/obs/sailfishos:/chum:/testing/5.1.0.11_armv7hl/

      - name: Show RPM
        run: |
          find RPMS -type f -name "*.rpm" -print
